FROM rustlang/rust:nightly as builder

WORKDIR /usr/src/daemon

COPY ./daemon .

RUN cargo install --path .

FROM debian:bullseye-slim
# RUN apt-get update && rm -rf /var/lib/apt/lists/*
RUN apt-get update
# RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
RUN apt-get install -y ca-certificates libssl3
COPY --from=builder /usr/local/cargo/bin/daemon /usr/local/bin/daemon

CMD ["daemon"]
